<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineRepository extends \Doctrine\ORM\EntityRepository
{

  public function getAll(){ //Requête pour la recherche

    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

     $qb->select(array('d', 'sd'))
     ->from('AppBundle\Entity\Domaine', 'd')
     ->join('d.structure', 'sd');

    $query = $qb->getQuery();
    $results = $query->getResult();

    return $results;

  }

  public function findone($nomDomaine) {   //requête pour la recherche à partir d'un nom de domaine

    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

     $qb->select(array('D'))
     ->from('AppBundle\Entity\Domaine', 'D')
     ->where('D.id = :id')
     ->setParameter('id', $nomDomaine);

    $query = $qb->getQuery();
    $results = $query->getResult();

    return $results;


  }
}
