<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * HebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergementRepository extends \Doctrine\ORM\EntityRepository
{
  public function getAll(){ // Requête pour la recherche

    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

     $qb->select(array('h', 's'))
     ->from('AppBundle\Entity\Hebergement', 'h')
     ->leftjoin('h.serveur', 's');

    $query = $qb->getQuery();
    $results = $query->getResult();

return $results;

  }

  public function findone($URL) { //Requête pour la recherche par URL

    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

     $qb->select(array('h'))
     ->from('AppBundle\Entity\Hebergement', 'h')
     ->where('h.id = :id')
     ->setParameter('id', $URL);

    $query = $qb->getQuery();
    $results = $query->getResult();

    return $results;


  }
}
