<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{

  public function getAll(){ //Requête pour les RechercheSousDomaine
    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

     $qb->select(array('p', 't'))
     ->from('AppBundle\Entity\Projet', 'p')
     ->leftjoin('p.typeProjet', 't');


    $query = $qb->getQuery();
    $results = $query->getResult();

    return $results;

  }



  public function findone($nomProjet) { // Recherche par nom de projet

    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

     $qb->select(array('p', 't'))
     ->from('AppBundle\Entity\Projet', 'p')
     ->leftjoin('p.typeProjet', 't')
     ->where('p.id = :id')
     ->setParameter('id', $nomProjet);

    $query = $qb->getQuery();
    $results = $query->getResult();

    return $results;

}
}
